import type { Metadata } from 'next'
import './globals.css'
import SubContent from '@/layout/SubContent'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en"> 
      <body className='h-dvh'>
      <div className='bg-WDS-emerald-500 h-1/6 absolute top-0 right-0 left-0 z-10'/>
        <div className=' bg-[#f0f2f5] shadow-lg z-20 absolute h-[calc(100%-2.375rem)] w-[calc(100%-2.375rem)] top-1/2 right-1/2 translate-x-1/2 translate-y-[-50%] flex'>
            <SubContent/>
            <div className='flex w-9/12 border-solid border-l-[0.8px] border-[#d1d7db]'>
              {children}
            </div>
        </div>
      </body>
    </html>
  )
}
